CREATE TABLE student (
    roll_no INT PRIMARY KEY,
    name VARCHAR(50),
    city VARCHAR(50),
    marks INT,
    subject VARCHAR(50));
	INSERT INTO student (roll_no, name, city, marks, subject) VALUES
(1, 'John Doe', 'Pune', 85, 'Mathematics'),
(2, 'Jane Smith', 'Mumbai', 92, 'Science'),
(3, 'Ali Khan', 'Delhi', 78, 'History'),
(4, 'Maria Rodriguez', 'Kolkata', 88, 'Geography'),
(5, 'Liu Wang', 'Chennai', 95, 'Physics'),
(6, 'Sofia Verma', 'Hyderabad', 81, 'English'),
(7, 'Aarav Patel', 'Ahmedabad', 83, 'Chemistry'),
(8, 'Aisha Gupta', 'Bangalore', 90, 'Biology'),
(9, 'Mikhail Ivanov', 'Chandigarh', 76, 'Mathematics'),
(10, 'Yuko Tanaka', 'Nagpur', 89, 'Science'),
(11, 'Rajesh Mehta', 'Bhopal', 77, 'History'),
(12, 'Neha Sharma', 'Jaipur', 85, 'Geography'),
(13, 'Carlos Mendoza', 'Lucknow', 93, 'Physics'),
(14, 'Fatima Ahmed', 'Patna', 79, 'English'),
(15, 'Jin Park', 'Bhubaneswar', 82, 'Chemistry'),
(16, 'Emily Clark', 'Guwahati', 91, 'Biology'),
(17, 'Ravi Kumar', 'Indore', 84, 'Mathematics'),
(18, 'Anjali Singh', 'Thiruvananthapuram', 87, 'Science'),
(19, 'Leonardo Costa', 'Mysore', 75, 'History'),
(20, 'Meera Krishnan', 'Coimbatore', 92, 'Geography'),
(21, 'Pedro Garcia', 'Vadodara', 80, 'Physics'),
(22, 'Simran Kaur', 'Vijayawada', 88, 'English'),
(23, 'Mohammad Hassan', 'Dehradun', 86, 'Chemistry'),
(24, 'Sarah Johnson', 'Ranchi', 89, 'Biology'),
(25, 'Takashi Yamamoto', 'Vellore', 94, 'Mathematics'),
(26, 'Eva Novak', 'Jodhpur', 81, 'Science'),
(27, 'Vikram Desai', 'Agra', 90, 'History'),
(28, 'Anita Kapoor', 'Raipur', 78, 'Geography'),
(29, 'Chinwe Okafor', 'Shillong', 91, 'Physics'),
(30, 'Kiran Mishra', 'Udaipur', 87, 'English');
INSERT INTO student (roll_no, name, city, marks, subject) VALUES
(1, 'John Doe', 'Pune', 85, 'Mathematics'),
(2, 'Jane Smith', 'Mumbai', 92, 'Science'),
(3, 'Ali Khan', 'Delhi', 78, 'History'),
(4, 'Maria Rodriguez', 'Kolkata', 88, 'Geography'),
(5, 'Liu Wang', 'Chennai', 95, 'Physics'),
(6, 'Sofia Verma', 'Hyderabad', 81, 'English'),
(7, 'Aarav Patel', 'Ahmedabad', 83, 'Chemistry'),
(8, 'Aisha Gupta', 'Bangalore', 90, 'Biology'),
(9, 'Mikhail Ivanov', 'Chandigarh', 76, 'Mathematics'),
(10, 'Yuko Tanaka', 'Nagpur', 89, 'Science'),
(11, 'Rajesh Mehta', 'Bhopal', 77, 'History'),
(12, 'Neha Sharma', 'Jaipur', 85, 'Geography'),
(13, 'Carlos Mendoza', 'Lucknow', 93, 'Physics'),
(14, 'Fatima Ahmed', 'Patna', 79, 'English'),
(15, 'Jin Park', 'Bhubaneswar', 82, 'Chemistry'),
(16, 'Emily Clark', 'Guwahati', 91, 'Biology'),
(17, 'Ravi Kumar', 'Indore', 84, 'Mathematics'),
(18, 'Anjali Singh', 'Thiruvananthapuram', 87, 'Science'),
(19, 'Leonardo Costa', 'Mysore', 75, 'History'),
(20, 'Meera Krishnan', 'Coimbatore', 92, 'Geography'),
(21, 'Pedro Garcia', 'Vadodara', 80, 'Physics'),
(22, 'Simran Kaur', 'Vijayawada', 88, 'English'),
(23, 'Mohammad Hassan', 'Dehradun', 86, 'Chemistry'),
(24, 'Sarah Johnson', 'Ranchi', 89, 'Biology'),
(25, 'Takashi Yamamoto', 'Vellore', 94, 'Mathematics'),
(26, 'Eva Novak', 'Jodhpur', 81, 'Science'),
(27, 'Vikram Desai', 'Agra', 90, 'History'),
(28, 'Anita Kapoor', 'Raipur', 78, 'Geography'),
(29, 'Chinwe Okafor', 'Shillong', 91, 'Physics'),
(30, 'Kiran Mishra', 'Udaipur', 87, 'English');

-- Query to display the data
SELECT * FROM student;

INSERT INTO student (roll_no, name, city, marks, subject) VALUES
(31, 'Sumit Agarwal', 'Gurgaon', 82, 'Chemistry'),
(32, 'Priya Chatterjee', 'Surat', 89, 'Biology'),
(33, 'Ethan Williams', 'Bhubaneswar', 77, 'Mathematics'),
(34, 'Arjun Rao', 'Kanpur', 91, 'Science'),
(35, 'Nisha Nair', 'Vadodara', 80, 'History'),
(36, 'Ritika Deshpande', 'Solapur', 87, 'Geography'),
(37, 'Amir Sheikh', 'Warangal', 88, 'Physics'),
(38, 'Zara Hussain', 'Mangalore', 84, 'English'),
(39, 'Harish Iyer', 'Kochi', 90, 'Chemistry'),
(40, 'Isabella Martin', 'Nasik', 92, 'Biology'),
(41, 'Karan Sethi', 'Puducherry', 86, 'Mathematics'),
(42, 'Gautam Singh', 'Allahabad', 83, 'Science'),
(43, 'Nikita Sharma', 'Gwalior', 79, 'History'),
(44, 'Leon Sanchez', 'Amritsar', 85, 'Geography'),
(45, 'Anya Patel', 'Jabalpur', 91, 'Physics'),
(46, 'Sahil Jain', 'Faridabad', 82, 'English'),
(47, 'Lisa Fernandes', 'Jamshedpur', 88, 'Chemistry'),
(48, 'Noah Brown', 'Meerut', 87, 'Biology'),
(49, 'Rehan Malhotra', 'Ghaziabad', 84, 'Mathematics'),
(50, 'Kiara Kapoor', 'Panaji', 93, 'Science')
select * from student
select subject , avg (marks) from student 
where name like'[a,p,k,c]%' and roll_no between 31 and 50 and city<>'mumbai' 
group by subject having avg(marks) between 80 and 100 order by avg(marks) desc